[project]
name = "video-ds-and-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "ipython>=8.32.0",
    "numpy>=2.2.2",
    "pandas>=2.2.3",
]
