preprocess:
  input_data: ./data/video_emotion_sample.csv
  video_dir: ./data/video_data/
  label_column: sentiments_name
  feature_columns:
    - video_id
  n_splits: 2
  test_size: 0.2
  interval_sec: 2
  seed: 42

model:
  use_model: VideoMAE
  VideoMAE:
    num_frames: 16
    image_size: 224
    image_mean: [0.485, 0.456, 0.406]
    image_std: [0.229, 0.224, 0.225]
    padding_mask: True
    model_kwargs:
      model_path: MCG-NJU/videomae-base
      use_memory_efficient_attention: True

train:
  loss: ce # ce: CrossEntropyLoss, mse: MeanSquaredError, bce: BinaryCrossEntropy
  output_dir: ./output/
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  gradient_accumulation_steps: 1
  evaluation_strategy: steps # steps, epoch
  eval_steps: 3
  lr: 1.0e-4
  lr_scheduler_type: cosine # cosine, linear, constant_with_warmup
  warmup_steps: 0 # 'constant_with_warmup'の学習率のwarmupのステップ数:0はwarmupなし
  weight_decay: 0.0 # 重み減衰率
  warmup_steps: 0
  num_train_epochs: 3
  disable_trainer_tqdm: false
  predicsion_type: fp16 # fp16, fp32, bf16
  num_workers: 4
  early_stopping_patience: 20 # 学習早期停止を判断するのに検証何回先まで確認するかを指定

